### ISSUE TITLE
Make router.Transport decision on DeserializeException configurable

### ISSUE THREAD

**Issue by angiolep** [angiolep/akka-wamp#20]
Router shall be configured as follows:

```bash
akka {
  wamp {
    router {
       transport {
          # Decision to be made on DeserializeException can be 
          # one of the following two alternatives:
          # 
          #   - resume
          #      The offending message is dropped and the 
          #      stream continues to process the next one
          #   
          #   - stop
          #      The transport is stopped and client disconnected
          #
          deserialize-exception = resume
        }}}}
```

**Comment by luchesar** [comment]
* Would having such configuration allow connecting to different servers with different value for the `deserialize-exception` configuration e.g. I would like to connect ot wss://host1 with `resume` and to wss://host2 with `stop`
* How about adding a third option `restart` to the list `resume` and `stop`?

**Comment by angiolep** [comment]
Hi luchesar,

**Comment by angiolep** [comment]
My replies:

1. It seems you need to write a WAMP process which connects to more than one WAMP router with different message handling settings: one that resumes on deserialize exception and the other which disconnect. This WAMP process with multiple clients behaving differently would be much easier to implement it if you could 

  * write it using the Future base API ([read the docs](http://akka-wamp.readthedocs.io/en/latest/client/future/))
  * branch off [v0.8.0](https://github.com/angiolep/akka-wamp/releases/tag/v0.8.0) 
  * and enhance the ``akka.wamp.client.Client`` factory methods as described by issue #31

2. ``Supervision.Restart`` works in a similar way as ``Supervision.Resume`` with the addition that accumulated state, if any, of the failing processing stage (of the underlying Akka Stream) will be reset ... but there's no accumulated state in Akka Wamp! Therefore, restart seems to be useless in our specific case.

3. That would be a _fine grained_ configuration we could provide as further enhancement for future Akka Wamp releases ... better to keep configuration simple for the time being. Let's go with the following easy configuration:

```bash
akka {
  wamp {
     client {
      # The boolean switch to disconnect those peers that send 
      # offending messages (e.g. not deserializable or causing
      # session failures)
      #
      # By default, offending messages are just dropped and 
      # the router resumes processing next incoming messages
      #
      disconnect-offending-peers = false
}}}
```

**Comment by angiolep** [comment]
Provided in [v0.8.0](https://github.com/angiolep/akka-wamp/releases/tag/v0.8.0)
