### ISSUE TITLE
Implement the deserialization of streamed text messages in JsonSerializationFlows

### ISSUE THREAD

**Issue by asciiu** [angiolep/akka-wamp#27]
This seems to not be implemented right now. The current implementation:
          throw new DeserializeException("Cannot deserialize binary message as JSON message was expected instead!")

Needs to be:
          source.runFold("")(_ + _)(materializer)
            .map( json.deserialize(_)(validator, materializer) )(materializer.executionContext)

**Comment by angiolep** [comment]
Fixed in version 0.10.0

**Comment by angiolep** [comment]
Keep an eye on https://github.com/akka/akka/issues/21607
