### ISSUE TITLE
Not compatible with akka 2.5.2

### ISSUE THREAD

**Issue by tonyPo** [angiolep/akka-wamp#47]
Akkawamp 0.15.0 is not compatible with akka 2.5.2. Would it be possible to upgrade akkawamp to make it compatible with 2.5.2

**Comment by angiolep** [comment]
Akka Wamp is strongly coupled to Akka Http. Therefore it can evolve at the same pace of Akka Http.
At the time of this writing, the latest version of Akka Http is **10.0.7** which in turn depends on Akka Actor **2.4.18**

For that reason Akka Wamp needs to be used with Akka Actor **2.4.18** although a newer version (the 2.5.2) has been already published to Maven central.

I'm sorry we'll need to wait few months for Akka Http to be upgraded.

**Comment by tonyPo** [comment]
Hi  Angiole,

Thank you for your update.
I’m very new to Akka, but just to double check. I’m using akka http as well in m project, together with akka 2.5.2.
The ‘migration’ guide does say that you also need to include akka streams in that case. Can this be the problem?
According to the release notes it should be compatible with at least 2.5.1
http://akka.io/blog/news/2017/05/25/akka-http-10.0.7-released

Btw I noticed that version 10.0.8 is released on the 20th and available in the docs.
http://akka.io/blog/

Thank you very much

Regards,

Ton

**Comment by raboof** [comment]
Indeed akka-http depends on akka 2.4.x, but since Akka is backwards compatible it should also work with Akka 2.5.x. This should also be the case for your project, unless you touched some internal API. Do you run into any actual problems when you depend on Akka 2.5.x explicitly?

**Comment by ktoso** [comment]
You absolutely can use it with 2.5, here's docs: https://doc.akka.io/docs/akka-http/current/scala/http/compatibility-guidelines.html#akka-http-10-0-x-with-akka-2-5-x

**Comment by angiolep** [comment]
Thank you @ktoso and @raboof 
I will certainly try as per your advice

**Comment by angiolep** [comment]
I made Akka Wamp explicitly depend on 

- Akka HTTP 10.1.0
- Akka Stream 2.5.11

as documented in the [Akka HTTP docs](https://doc.akka.io/docs/akka-http/current/release-notes/10.1.x.html#akka-is-not-an-explicit-dependency-anymore-removal-of-akka-2-4-support)

**Comment by angiolep** [comment]
I made Akka Wamp explicitly depend on 

- Akka HTTP 10.1.0
- Akka Stream 2.5.11

as documented in the [Akka HTTP docs](https://doc.akka.io/docs/akka-http/current/release-notes/10.1.x.html#akka-is-not-an-explicit-dependency-anymore-removal-of-akka-2-4-support)
