### ISSUE TITLE
Poloniex example doesnt work

### ISSUE THREAD

**Issue by coolemza** [angiolep/akka-wamp#50]
tried poloniex example, it doesn work:

21:57:49.293 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisignclass2g2ca [jdk]: Certificate failed: cert = "OU=VeriSign Trust Network,OU=(c) 1998 VeriSign\, Inc. - For authorized use only,OU=Class 2 Public Primary Certification Authority - G2,O=VeriSign\, Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.306 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisigntsaca [jdk]: Certificate failed: cert = "CN=Thawte Timestamping CA,OU=Thawte Certification,O=Thawte,L=Durbanville,ST=Western Cape,C=ZA" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.307 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in gtecybertrustglobalca [jdk]: Certificate failed: cert = "CN=GTE CyberTrust Global Root,OU=GTE CyberTrust Solutions\, Inc.,O=GTE Corporation,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.307 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisignclass3g2ca [jdk]: Certificate failed: cert = "OU=VeriSign Trust Network,OU=(c) 1998 VeriSign\, Inc. - For authorized use only,OU=Class 3 Public Primary Certification Authority - G2,O=VeriSign\, Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.307 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in equifaxsecureglobalebusinessca1 [jdk]: Certificate failed: cert = "CN=Equifax Secure Global eBusiness CA-1,O=Equifax Secure Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.312 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in thawtepremiumserverca [jdk]: Certificate failed: cert = "1.2.840.113549.1.9.1=#16197072656d69756d2d736572766572407468617774652e636f6d,CN=Thawte Premium Server CA,OU=Certification Services Division,O=Thawte Consulting cc,L=Cape Town,ST=Western Cape,C=ZA" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.312 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisignclass1g2ca [jdk]: Certificate failed: cert = "OU=VeriSign Trust Network,OU=(c) 1998 VeriSign\, Inc. - For authorized use only,OU=Class 1 Public Primary Certification Authority - G2,O=VeriSign\, Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.312 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisignclass3ca [jdk]: Certificate failed: cert = "OU=Class 3 Public Primary Certification Authority,O=VeriSign\, Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.312 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in verisignclass1ca [jdk]: Certificate failed: cert = "OU=Class 1 Public Primary Certification Authority,O=VeriSign\, Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.313 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in equifaxsecureebusinessca1 [jdk]: Certificate failed: cert = "CN=Equifax Secure eBusiness CA-1,O=Equifax Secure Inc.,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:49.313 |-WARN  in c.t.s.s.ConfigSSLContextBuilder - validateStore: Skipping certificate with weak key size in equifaxsecureca [jdk]: Certificate failed: cert = "OU=Equifax Secure Certificate Authority,O=Equifax,C=US" failed on constraint RSA keySize < 2048, algorithm = RSA, keySize = 1024
21:57:50.714 |-ERROR in a.a.LocalActorRefProvider(akka://default) - guardian failed, shutting down system
akka.wamp.client.ClientException: WebSocket upgrade did not finish because of 'unexpected status code: 502 Bad Gateway'

**Comment by angiolep** [comment]
First of all, thanks for using akka-wamp and for filing this issue.

Please ignore WARNings as they are not harmful. Those are just telling you that some of the certificates found in some of the (well known by your underlying JVM) certificate chains have been signed with weak keys (those whose size is less than a configurable amount). If you wish to better understand it then read https://www.java.com/en/configure_crypto.html#disableSHA1

The only interesting part of your copied-and-pasted output is

```
21:57:50.714 |-ERROR in a.a.LocalActorRefProvider(akka://default) - guardian failed, shutting down system
akka.wamp.client.ClientException: WebSocket upgrade did not finish because of 'unexpected status code: 502 Bad Gateway'
```

which I have not been able to replicate on my development environment.

Make sure you already got Git and SBT correctly installed on your local development environment. Then try the following, please:

```sh
git clone https://github.com/angiolep/akka-wamp.git
cd akka-wamp
git checkout release-0.15.x
sbt
```

Then in the SBT shell, try with:

```sh
> project poloniex
> run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] PoloniexJavaClient
 [2] PoloniexScalaClient

Enter number: 
```

choose whatever client you like and let me know how it works, please.
